config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root :to => 'home#index'
  get '/user/:id' => 'home#user'
  resources :conversations do
    resources :messages
  end

  resources :forums do
    resources :forum_messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id, recipient_id) {
    where(sender_id: sender_id, recipient_id: recipient_id).or(where(sender_id: recipient_id, recipient_id: sender_id))
  }

  scope :userMessages, -> (user_id) {
    where(sender_id: user_id).or(where(recipient_id: user_id))
  }
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :forum_messages
  has_many :users, through: :forum_messages

  validates :title, presence: true
  validates :description, presence: true
end

app/models/forum_message.rb
class ForumMessage < ApplicationRecord
  belongs_to :user
  belongs_to :forum

  validates :title, presence: true
  validates :body, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  scope :unread, -> {
    where("read = false")
  }

  def message_time
    created_at.strftime('%F at %H:%M')
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :normalize_params, on: [:create, :update]

  has_many :conversations, :foreign_key => :sender_id, class_name: 'Conversation'
  has_many :conversations, :foreign_key => :recipient_id, class_name: 'Conversation'

  has_many :messages, through: :conversations

  validates :email, :presence => true
  validates :email, :uniqueness => true

  validates :username, :presence => true
  validates :username, :uniqueness => true

  validates_confirmation_of :password

  scope :all_users_except, -> (current_user) {
    where.not(id: current_user)
  }

  scope :all_available_crew, -> {
    where(:account_type => 'Crew', :available => 'Available')
  }

  scope :all_available_captains, -> {
    where(:account_type => 'Captain', :available => 'Available')
  }

  scope :search, -> (search_parameter) {
    where("lower(home) like lower(?) OR lower(name) like lower(?) OR lower(username) like lower(?) OR lower(detail) like lower(?)", "%#{search_parameter}%", "%#{search_parameter}%", "%#{search_parameter}%", "%#{search_parameter}%")
  }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

  def normalize_params
    self.name = name.downcase.titleize if attribute_present? 'name'
    self.email = email.downcase if attribute_present? 'email'
    self.home = home.downcase.titleize if attribute_present? 'home'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      added_attrs = [:username, :email, :name, :home, :age, :experience, :avatar, :available, :account_type, :detail, :password, :password_confirmation, :remember_me]
      update_attrs = [:username, :email, :name, :home, :age, :experience, :avatar, :available, :account_type, :detail, :password, :password_confirmation, :current_password]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: update_attrs
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],
      params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/forum_messages_controller.rb
class ForumMessagesController < ApplicationController
  def create
    @forum = Forum.find(params[:forum_id])
    x = params[:forum_message]
    @message = ForumMessage.new(user_id: x[:user_id], forum_id: @forum.id, title: x[:title], body: x[:body])
    if @message.save
      respond_to do |format|
        format.html { redirect_to forums_path(@forum) }
        format.js
      end
    end
  end

  private
  def message_params
    params.permit(:user_id, :forum_id, :title, :body)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @user = User.find(@forum.user_id)
    @messages = @forum.forum_messages
    @message = ForumMessage.new(message_params)
  end

  private
  def message_params
    params.permit(:user_id, :forum_id, :title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @crew = User.all_users_except(current_user).all_available_crew
    @captains = User.all_users_except(current_user).all_available_captains

    if params[:search] != nil
      @crew = User.all_users_except(current_user).all_available_crew.search(params[:search])
      @captains = User.all_users_except(current_user).all_available_captains.search(params[:search])
    end
  end

  def user
    @user = User.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages

    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.where('user_id != ?', current_user.id).update(read: true)
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to conversation_messages_path(@conversation) }
        format.js
      end
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :user_id, :read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mail_helper.rb
module MailHelper
  def mail_set(user)
    userConv = Conversation.userMessages(user.id)
    userMessages = [];
    userConv.each do |c|
      c.messages.unread.each do |m|
        if m.user_id != user.id
          userMessages = userMessages.push(m)
        end
      end
    end
    return userMessages.count
  end

  def mail_count(user1, user2)
    userConv = Conversation.userMessages(user1.id)
    userMessages = [];
    userConv.each do |c|
      c.messages.unread.each do |m|
        if m.user_id != user1.id && m.user_id == user2.id
          userMessages = userMessages.push(m)
        end
      end
    end
    return userMessages.count
  end
end

app/views/conversations/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <h3>Your Conversations:</h3>
      <div class=”list”>
        <div class=”item”>
          <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
              <% if conversation.sender_id == current_user.id %>
                <% recipient = User.find(conversation.recipient_id) %>
              <% else %>
                <% recipient = User.find(conversation.sender_id) %>
              <% end %>
              <li>
                <%= link_to conversation_messages_path(conversation), class: 'nav-link' do %>
                  <%= recipient.username %> (<%= mail_count(current_user, recipient) %>)
                <% end %>
              </li>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <h3>Start New Conversation:</h3>
      <div class=”list”>
        <% @users.each do |user| %>
          <% if user.id != current_user.id %>
            <div class=”item”>
              <%= user.username %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/forum_messages/create.js.erb
$("#messWriteDiv").load('<%= @forum.id %> #textWriteCard');
$("#forumMess").load('<%= @forum.id %> #forumMessCard');

app/views/forums/index.html.erb
<% if @forums.any? %>
  <div class="card">
    <h4>Forums:</h4>
    <hr>
    <% @forums.each do |f| %>
      <div class="row">
        <div class="col-md-9">
          <li><%= link_to f.title, :controller => "forums", :action => "show", :id => f.id %></li>
          <li><%= f.description %></li>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
<% end %>

app/views/forums/show.html.erb
<% if @messages.any? %>
  <div id="forumMess">
    <div class="card" id="forumMessCard">
      <h4><li><%= @forum.title %></li></h4>
      <small>Forum Author: <%= @user.username %></small>
      <hr>
      <% @messages.each do |m| %>
        <div class="row">
          <div class="col-md-9">
            <% user = User.find(m.user_id)%>
            <li><%= m.title %></li>
            <li><%= m.body %></li>
            <li>Author: <%= user.username %></li>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
<% end %>

<div id="messWriteDiv">
  <div id="textWriteCard" class="card">
    <%= form_for [@forum, @message], remote: true do |f| %>
      <%= f.label :title %>
      <br>
      <%= f.text_area :title, :rows => 1, style: 'width:30%;', class: 'formBack' %>
      <br>
      <%= f.label :body %>
      <br>
      <%= f.text_area :body, :rows => 10, style: 'width:100%;', class: 'formBack' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div>
        <%= f.submit class: 'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <% if @crew.any? %>
    <div class="col-md-6">
      <div class="card">
        <h4>Available Crew:</h4>
        <hr>
        <% @crew.each do |u| %>
          <div class="row">
            <div class="col-md-3">
              <li class='round-image-50'><%= image_tag(u.avatar.url(:thumb)) %></li>
              <li><%= link_to u.username, :controller => "home", :action => "user", :id => u.id %></li>
            </div>
            <div class="col-md-9">
              <li><%= u.detail %></li>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @captains.any? %>
    <div class="col-md-6">
      <div class="card">
        <h4>Available Positions:</h4>
        <hr>
        <% @captains.each do |u| %>
          <div class="row">
            <div class="col-md-3">
              <li class='round-image-50'><%= image_tag(u.avatar.url(:thumb)) %></li>
              <li><%= link_to u.username, :controller => "home", :action => "user", :id => u.id %></li>
            </div>
            <div class="col-md-9">
              <li><%= u.detail %></li>
            </div>
          </div>
          <br>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/user.html.erb
<div class="card">
  <div class="row">
    <div class="col-md-6">
      <h4><%= @user.name %></h4>
      <div class="userDet">
        <%= image_tag(@user.avatar.url(:medium)) %>
      </div>
    </div>
    <div class="col-md-6">
      <p>Description:</p>
      <p><%= @user.detail %></p>
      <br>
      <h5>About Me:</h5>
      <p>Home Country: <%= @user.home %></p>
      <p>Age: <%= @user.age %></p>
      <p>Years of Experience: <%= @user.experience %></p>
      <p>Username: <%= @user.username %></p>
      <p>Availability: <%= @user.available %></p>
      <p>Acount Type: <%= @user.account_type %></p>
      <% if current_user %>
        <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post'%>
      <% else %>
        <p>Log in to message me!</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crewmates</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Lobster+Two');
  </style>
  <header>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div id="crewMates">
        <nav class="navbar-brand"><%= link_to 'CrewMates', root_path, class: 'nav-link' %></nav>
      </div>
      <ul class="navbar-nav">
        <% if current_user %>
          <div class='round-image-50'><%= image_tag(current_user.avatar.url(:thumb)) %></div>
          <li class="nav-item"><%= link_to current_user.username, edit_user_registration_path, class: 'nav-link' %></li>
          <li id="mCount" class="nav-item">
            <%= link_to conversations_path, class: 'nav-link' do %>
              Mailbox (<%= mail_set(current_user) %>)
            <% end %>
          </li>
          <li class="nav-item"><%= link_to 'Forums', forums_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% if current_user.admin %>
            <li class="nav-item"><%= link_to 'Admin', rails_admin_path, class: 'nav-link' %></li>
          <% end %>
        <% else %>
          <li class="nav-item"><%= link_to 'Forums', forums_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link'  %></li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <%= form_tag(root_path, :method => "get", :class => "form-inline my-2 my-lg-0") do %>
          <%= text_field_tag :search, params[:search],  :class => "formBack form-control mr-sm-2" %>
          <%= submit_tag "Search", :class => "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      </div>
      </ul>
    </nav>
  </header><br>

  <body class="mainBack">
    <div class='container'>
      <% flash.each do |key, value| %>
        <div class='alert alert-dismissible fade show card alertCard' role='alert'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <li aria-hidden="true">&times;</li>
          </button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
</body>
</html>

app/views/messages/create.js.erb
$("#messDiv").load('messages #messCard');
$("#writeDiv").load('messages #textCard');

app/views/messages/index.html.erb
<div class="row">
  <div id="messDiv" class="col-md-6">
    <div id="messCard" class="card">
      <h4>Messages: </h4>
      <% @messages.each do |message| %>
        <% if message.content %>
          <% user = User.find(message.user_id) %>
          <div class=”item”>
            <div class=”content”>
              <% if user == current_user %>
                <small><strong class="myMess"><%= user.username %></strong> <%= message.message_time %></small>
              <% else %>
                <small><strong class="theirMess"><%= user.username %></strong> <%= message.message_time %></small>
              <% end %>
                <div class=”list”>
                  <div class=”item”>
                  <i class=”right triangle icon”></i>
                  <%= message.content %>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="writeDiv" class="col-md-6">
    <div id="textCard" class="card">
      <%= form_for [@conversation, @message], remote: true do |f| %>
        <%= f.text_area :content, :rows => 10, style: 'width:100%;', class: 'formBack' %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div>
          <%= f.submit class: 'btn btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>